### ISSUE TITLE
[Dependencies] Build fails given current dependency constraints

### ISSUE THREAD

**Issue by emlautarom1** [owickstrom/gi-gtk-declarative#89]
As you can see on [this SO question](https://stackoverflow.com/questions/64761054/trying-to-compile-gi-gtk-declarative/65100094#65100094), currently this library fails to build given a third party dependency.

[The upstream issue was this one and it's already fixed](https://github.com/haskell-gi/haskell-gi/issues/318)

Regarding this library:
- In the dependencies, it's specified: `haskell-gi (>=0.21 && <0.24)`
- The build issue was fixed on `haskell-gi 0.24.4` which can't be used given the constraints

The current workaround is running `stack build --allow-newer` or `cabal build --allow-newer`, but this is far from ideal.

In my pet program, everything looks fine, so I can't be sure that bumping the dependencies won't break anything

**Comment by mnn** [comment]
> The current workaround is running `stack build --allow-newer`

```sh
$ stack build --allow-newer
Invalid option `--allow-newer'

Usage: stack build [TARGET] [--dry-run] [--pedantic] [--fast]
                   [--ghc-options OPTIONS] [--flag PACKAGE:[-]FLAG]
                   ([--dependencies-only] | [--only-snapshot] |
                   [--only-dependencies] | [--only-locals]) ([--file-watch] |
                   [--file-watch-poll]) [--watch-all]
                   [--exec COMMAND [ARGUMENT(S)]] [--only-configure] [--trace]
                   [--profile] [--no-strip] [--[no-]library-profiling]
                   [--[no-]executable-profiling] [--[no-]library-stripping]
                   [--[no-]executable-stripping] [--[no-]haddock]
                   [--haddock-arguments HADDOCK_ARGS] [--[no-]open]
                   [--[no-]haddock-deps] [--[no-]haddock-internal]
                   [--[no-]haddock-hyperlink-source] [--[no-]copy-bins]
                   [--[no-]copy-compiler-tool] [--[no-]prefetch]
                   [--[no-]keep-going] [--[no-]keep-tmp-files]
                   [--[no-]force-dirty] [--[no-]test] [--[no-]rerun-tests]
                   [--ta|--test-arguments TEST_ARGS] [--coverage]
                   [--no-run-tests] [--test-suite-timeout ARG] [--[no-]bench]
                   [--ba|--benchmark-arguments BENCH_ARGS] [--no-run-benchmarks]
                   [--[no-]reconfigure] [--[no-]cabal-verbose]
                   [--[no-]split-objs] [--skip ARG] [--[no-]interleaved-output]
                   [--ddump-dir ARG] [--setup-info-yaml URL]
                   [--snapshot-location-base URL] [--help]
  Build the package(s) in this directory/configuration
```

Am I missing something?

**Comment by toasterbath255** [comment]
AFAIK  `--allow-newer` is not a stack command line option, it should be supplied via global or local stack config file.
For example
```
# my-project/stack.yaml
allow-newer: true
```

However, with `allow-newer: true`, I couldn't get it built. It still produces error `Unknown GIR element "docsection" when processing namespace "GLib", aborting.`

**Comment by mnn** [comment]
I tried `allow-newer: true` in project `stack.yaml` too and same as @toasterbath255 it didn't have any impact (same error as without, `stack clean` didn't help either). Searching more, I suspect `allow-newer` may have been removed from stack entirely.

**Comment by toasterbath255** [comment]
I think `allow-newer` option in `stack.yaml` is still valid, it was just not affecting the issue.

I don't know why but I can build `gi-glib` without a problem now (so I can build `gi-gtk`), but since `gi-gtk-declarative` requires older versions of `haskell-gi` and etc., I still needed `allow-newer: true` to build `gi-gtk-declarative`. Here's my snippets of working `stack.yaml` and `package.yaml`. ([it mostly copied from cited issue](https://github.com/haskell-gi/haskell-gi/issues/318#issuecomment-728548783))

```yaml
extra-deps:
- haskell-gi-base-0.24.4
- haskell-gi-0.24.5
- gi-glib-2.0.24
- gi-pango-1.0.23
- gi-harfbuzz-0.0.3
- gi-gtk-3.0.36
- gi-gtk-declarative-0.6.3
allow-newer: true
```

```yaml
executables:
  asdf-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - zxcv
    - gi-gtk-declarative
```

So yeah we have a workaround, but this issue still needs to be solved.

**Comment by mnn** [comment]
No luck with compiling Hello example. This is what I ended up with (I am noob at stack):

```yaml
extra-deps:
- haskell-gi-base-0.24.4
- haskell-gi-0.24.5
- gi-glib-2.0.24
- gi-pango-1.0.23
- gi-harfbuzz-0.0.3
- gi-gtk-3.0.36
- gi-gtk-declarative-0.6.3
- gi-gtk-declarative-app-simple-0.6.3
- pipes-extra-0.2.0
- pipes-core-0.1.0
- categories-1.0.7
allow-newer: true
```

```
$ stack run
WARNING: Ignoring pipes-extra's bounds on bytestring ((==0.9.*)); using bytestring-0.10.10.1.
Reason: allow-newer enabled.
WARNING: Ignoring pipes-core's bounds on lifted-base ((==0.1.*)); using lifted-base-0.2.3.12.
Reason: allow-newer enabled.
WARNING: Ignoring pipes-core's bounds on monad-control ((==0.3.*)); using monad-control-1.0.2.3.
Reason: allow-newer enabled.
WARNING: Ignoring pipes-core's bounds on transformers ((>=0.2 && <0.4)); using transformers-0.5.6.2.
Reason: allow-newer enabled.
WARNING: Ignoring pipes-core's bounds on void ((==0.5.*)); using void-0.7.3.
Reason: allow-newer enabled.
WARNING: Ignoring pipes-extra's bounds on transformers ((>=0.2 && <0.4)); using transformers-0.5.6.2.
Reason: allow-newer enabled.
pipes-core > configure
pipes-core > Configuring pipes-core-0.1.0...
pipes-core > build
pipes-core > Preprocessing library for pipes-core-0.1.0..
pipes-core > Building library for pipes-core-0.1.0..
pipes-core > [1 of 7] Compiling Control.Category.Multiplicative
pipes-core >
pipes-core > /tmp/stack-c7a0667088f509df/pipes-core-0.1.0/Control/Category/Multiplicative.hs:23:3: error:
pipes-core >     • Couldn't match type ‘Id k p0’ with ‘Id k p’
pipes-core >       Expected type: k (Id k p) a
pipes-core >         Actual type: k (Id k p0) a
pipes-core >       NB: ‘Id’ is a non-injective type family
pipes-core >       The type variable ‘p0’ is ambiguous
pipes-core >     • In the ambiguity check for ‘unit’
pipes-core >       To defer the ambiguity check to use sites, enable AllowAmbiguousTypes
pipes-core >       When checking the class method:
pipes-core >         unit :: forall (k :: * -> * -> *) (p :: * -> * -> *) a.
pipes-core >                 Multiplicative k p =>
pipes-core >                 k (Id k p) a
pipes-core >       In the class declaration for ‘Multiplicative’
pipes-core >    |
pipes-core > 23 |   unit :: k (Id k p) a
pipes-core >    |   ^^^^^^^^^^^^^^^^^^^^
pipes-core >
Progress 1/3

--  While building package pipes-core-0.1.0 (scroll up to its section to see the error) using:
      /home/xxx/.stack/setup-exe-cache/x86_64-linux-tinfo6/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.4 --builddir=.stack-work/dist/x86_64-linux-tinfo6/Cabal-3.0.1.0 build --ghc-options " -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
```

I think I'll wait until it works on its own without hacks. I wanted to just try gi-gtk-declarative, but if a library is broken for a month then it's probably not maintained/mature enough for beginners like me.

**Comment by toasterbath255** [comment]
@mnn If you would like to give a go for the last time, would you try this code with config I commented above? It literally does nothing but open empty window.
```haskell
{-# LANGUAGE OverloadedLabels #-}
{-# LANGUAGE OverloadedLists #-}
{-# LANGUAGE OverloadedStrings #-}

module Main where

import Control.Monad (void)
import qualified GI.Gtk as Gtk
  ( Label (Label),
    Window (Window),
  )
import GI.Gtk.Declarative as Gtk
  ( Attribute ((:=)),
    bin,
    on,
    widget,
  )
import qualified GI.Gtk.Declarative.App.Simple as Gtk.App
  ( App (App),
    AppView,
    Transition (Exit, Transition),
    initialState,
    inputs,
    run,
    update,
    view,
  )

data State = State

data Event = EventEvent | EventClosed

update :: State -> Event -> Gtk.App.Transition State Event
update _ EventEvent = Gtk.App.Transition State (return Nothing)
update _ EventClosed = Gtk.App.Exit

view :: State -> Gtk.App.AppView Gtk.Window Event
view _ =
  Gtk.bin
    Gtk.Window
    [ #title := "Hello",
      on #deleteEvent (const (True, EventClosed)),
      #widthRequest := 400,
      #heightRequest := 300,
      #resizable := False
    ]
    (Gtk.widget Gtk.Label [])

main :: IO ()
main =
  void $
    Gtk.App.run
      Gtk.App.App
        { Gtk.App.update = update,
          Gtk.App.view = view,
          Gtk.App.inputs = [],
          Gtk.App.initialState = State
        }
```

It looks like stack cannot pick working version of some dependencies for `pipes-core` (caused by `allow-newer` I guess). Example I provided with only uses dependencies for opening empty windows, so it may get you started with minimal working version.

But as you add some libraries you need, there's chance that the error above occurs again, so let's hope author fix it..

**Comment by mnn** [comment]
@toasterbath255 Thank you for trying to resolve my issue. 

I started again from your configs and the simplified example. After adding `gi-gtk` and `gi-gtk-declarative-app-simple` to `package.yaml`, and `gi-gtk-declarative-app-simple-0.6.3` to `extra-deps` in `stack.yaml`, a plain window shows :smile:.

<div align="center">
<img width="465" alt="2020-12-11_13-13" src="https://user-images.githubusercontent.com/1975567/101902344-ca594e80-3bb2-11eb-8b5e-57f483a36881.png">
</div>

What for is the pipes package used? In the hello example it seems to work as a timer, isn't the package effectively a dependency, required for almost any non-trivial GUI? Or are there alternative (comparable) ways to achieve same features the pipes are providing?

**Comment by guygastineau** [comment]
Resolved as of #90
